apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-deployment
  namespace: k8s-program
  labels:
    app.kubernetes.io/name: resources-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: resources-microservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: resources-microservice
    spec:
      containers:
        - name: resources-container
          image: resources-microservice:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: RESOURCES_MS_NAME
              value: "resources-microservice"
            - name: RESOURCES_MS_PORT
              value: "8080"
            - name: RESOURCES_DB_URL
              value: "resources-db-service"
            - name: RESOURCES_DB_PORT
              value: "5433"
            - name: SONGS_MS_URL
              value: "songs-service"
            - name: SONGS_MS_PORT
              value: "8081"
            - name: ENABLE_EUREKA_CLIENT
              value: "false"
