apiVersion: v1
kind: Service
metadata:
  name: songs-db-service
  namespace: k8s-program
spec:
  type: ClusterIP
  selector:
    app: songs-db
  ports:
    - port: 5432
      targetPort: 5432


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: songs-db
  namespace: k8s-program
spec:
  serviceName: songs-db-service
  replicas: 1
  selector:
    matchLabels:
      app: songs-db
  template:
    metadata:
      labels:
        app: songs-db
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: songs-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: songs-secret
                  key: password
          volumeMounts:
            - name: songs-db-storage
              mountPath: /var/lib/postgresql/data
            - name: songs-init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: songs-init-sql
          configMap:
            name: songs-init-sql
  volumeClaimTemplates:
    - metadata:
        name: songs-db-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: hostpath
        resources:
          requests:
            storage: 1Gi
