apiVersion: v1
kind: Service
metadata:
  name: resources-service
  namespace: k8s-program
  labels:
    app.kubernetes.io/name: resources-microservice
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: resources-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
