apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-deployment
  namespace: k8s-program
  labels:
    app.kubernetes.io/name: songs-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: songs-microservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: songs-microservice
    spec:
      containers:
        - name: songs-container
          image: songs-microservice:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: songs-configmap
          volumeMounts:
            - name: songs-volume
              mountPath: /app/data
      volumes:
        - name: songs-volume
          persistentVolumeClaim:
            claimName: songs-pvc
