apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-deployment
  namespace: k8s-program
  labels:
    app.kubernetes.io/name: resources-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: resources-microservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: resources-microservice
    spec:
      containers:
        - name: resources-container
          image: resources-microservice:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: resources-configmap
