apiVersion: v1
kind: ConfigMap
metadata:
  name: songs-configmap
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservices-chart.labels" . | nindent 4 }}
data:
  SONGS_MS_NAME: "songs-microservice"
  SONGS_MS_PORT: "8081"
  SONGS_DB_URL: "songs-db-service"
  SONGS_DB_PORT: "5432"
  ENABLE_EUREKA_CLIENT: "false"
