apiVersion: v1
kind: PersistentVolume
metadata:
  name: songs-pv
  namespace: {{ .Values.namespace }}
  labels:
    storage.kubernetes.io/name: songs-microservice
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /data/songs
  persistentVolumeReclaimPolicy: Retain
