apiVersion: v1
kind: Service
metadata:
  name: songs-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: songs-microservice
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: songs-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
