apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /(songs)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: songs-service
                port:
                  number: 80
          - path: /(resources)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: resources-service
                port:
                  number: 80
