apiVersion: v1
kind: Service
metadata:
  name: resources-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: resources-microservice
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: resources-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
